# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore: '
    ignore:
      # We're stuck on rollup 3 until
      # https://github.com/FredKSchott/rollup-plugin-polyfill-node/pull/77 lands
      - dependency-name: 'rollup'
        update-types: ['version-update:semver-major']

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'
