name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm build

      - name: Pack
        run: npm pack

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: image-display-control-metadata-parser
          path: frameright-image-display-control-metadata-parser-*.tgz
          if-no-files-found: error

  spellchecker:
    name: Spellchecker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Spellchecker
        run: npm run spellcheck
