name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          # NOTES:
          # * automatically created, see
          #   https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          # * used for posting a report on the pull-request.
          # * Workflow permissions must be 'Read and write permissions' under
          #   https://github.com/AurelienLourot/image-display-control-metadata-parser/settings/actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
